from multi_armed_bandit import FiveArmedBanditEnv, EightArmedBanditEnv, TwentyArmedBanditEnv
from multi_armed_bandit_late_reward import FiveArmedBanditLateRewardEnv, EightArmedBanditLateRewardEnv, TwentyArmedBanditLateRewardEnv
from multi_armed_bandit_regret import FiveArmedBanditRegretEnv, EightArmedBanditRegretEnv, TwentyArmedBanditRegretEnv
from multi_armed_bandit_regret_late import FiveArmedBanditRegretLateEnv, EightArmedBanditRegretLateEnv, TwentyArmedBanditRegretLateEnv

from contextual_bandit import ContextualBanditEnv